TEST_KAFKA_BROKER = '172.19.0.3:9092'
ETHEREUM_ACCOUNT_GROUP = b'ethereum_account_group'
ETHEREUM_ACCOUNT_TOPIC = b'ethereum_account'
ETHEREUM_TX_GROUP = b'ethereum_tx_group'
ETHEREUM_TX_TOPIC = b'ethereum_tx'
ETHEREUM_BLOCK_GROUP = b'ethereum_block_group'
ETHEREUM_BLOCK_TOPIC = b'ethereum_block'
